# Generated by Django 5.2.3 on 2025-07-05 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to='')),
                ('owner_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doc')),
            ],
        ),
    ]
